site_name: Curso Fundamental Blockchain Insper

nav:
  - Introdução: intro.md
  - Bitcoin: btc.md
  - Blockchain: block.md
  - CryptoAssets: assets.md
  - Regulação: law.md
  - Escalabilidade: escala.md
  - Tech: tech.md

plugins:
  - search

theme:
  name: 'material'
  favicon: assets\images\emblema.png
  logo: assets\images\emblema.png
  features:
    - navigation.indexes
    - navigation.top
